# Constants for the Vestel VR Remote integration

DOMAIN = "vestel_vr_remote"

# List of key codes, their functions, and icons (Material Design Icons)
KEYS = [
	{"code": "1000", "function": "Digit 0", "icon": "mdi:numeric-0"},
	{"code": "1001", "function": "Digit 1", "icon": "mdi:numeric-1"},
	{"code": "1002", "function": "Digit 2", "icon": "mdi:numeric-2"},
	{"code": "1003", "function": "Digit 3", "icon": "mdi:numeric-3"},
	{"code": "1004", "function": "Digit 4", "icon": "mdi:numeric-4"},
	{"code": "1005", "function": "Digit 5", "icon": "mdi:numeric-5"},
	{"code": "1006", "function": "Digit 6", "icon": "mdi:numeric-6"},
	{"code": "1007", "function": "Digit 7", "icon": "mdi:numeric-7"},
	{"code": "1008", "function": "Digit 8", "icon": "mdi:numeric-8"},
	{"code": "1009", "function": "Digit 9", "icon": "mdi:numeric-9"},
	{"code": "1010", "function": "Back", "icon": "mdi:arrow-u-left-top"},
	{"code": "1011", "function": "Aspect Ratio", "icon": "mdi:aspect-ratio"},
	{"code": "1012", "function": "Power", "icon": "mdi:power"},
	{"code": "1013", "function": "Mute", "icon": "mdi:volume-mute"},
	{"code": "1014", "function": "Presets"},
	{"code": "1015", "function": "Language", "icon": "mdi:translate"},
	{"code": "1016", "function": "Volume Up", "icon": "mdi:volume-plus"},
	{"code": "1017", "function": "Volume Down", "icon": "mdi:volume-minus"},
	{"code": "1018", "function": "Info", "icon": "mdi:information"},
	{"code": "1019", "function": "Down", "icon": "mdi:chevron-down"},
	{"code": "1020", "function": "Up", "icon": "mdi:chevron-up"},
	{"code": "1021", "function": "Left", "icon": "mdi:chevron-left"},
	{"code": "1022", "function": "Right", "icon": "mdi:chevron-right"},
	{"code": "1024", "function": "Stop", "icon": "mdi:stop"},
	{"code": "1025", "function": "Play", "icon": "mdi:play"},
	{"code": "1027", "function": "Rewind", "icon": "mdi:rewind"},
	{"code": "1028", "function": "Forward", "icon": "mdi:fast-forward"},
	{"code": "1031", "function": "Subtitles", "icon": "mdi:closed-caption"},
	{"code": "1032", "function": "Channel Up", "icon": "mdi:arrow-up-box"},
	{"code": "1033", "function": "Channel Down", "icon": "mdi:arrow-down-box"},
	{"code": "1034", "function": "Swap", "icon": "mdi:swap-horizontal"},
	{"code": "1037", "function": "Exit", "icon": "mdi:close-box-outline"},
	{"code": "1040", "function": "Favorites", "icon": "mdi:star"},
	{"code": "1042", "function": "Timer", "icon": "mdi:timer"},
	{"code": "1043", "function": "Quick Menu", "icon": "mdi:menu-open"},
	{"code": "1045", "function": "Channel", "icon": "mdi:television-box"},
	{"code": "1046", "function": "App", "icon": "mdi:application"},
	{"code": "1047", "function": "EPG", "icon": "mdi:television-guide"},
	{"code": "1048", "function": "Menu", "icon": "mdi:menu"},
	{"code": "1049", "function": "Pause", "icon": "mdi:pause"},
	{"code": "1050", "function": "Yellow", "icon": "mdi:alpha-y-circle"},
	{"code": "1051", "function": "Record", "icon": "mdi:record-rec"},
	{"code": "1052", "function": "Blue", "icon": "mdi:alpha-b-circle"},
	{"code": "1053", "function": "OK", "icon": "mdi:check"},
	{"code": "1054", "function": "Green", "icon": "mdi:alpha-g-circle"},
	{"code": "1055", "function": "Red", "icon": "mdi:alpha-r-circle"},
	{"code": "1056", "function": "Source", "icon": "mdi:import"},
	{"code": "1057", "function": "Media Browser", "icon": "mdi:folder-play"},
	{"code": "1255", "function": "Teletext", "icon": "mdi:text-box"}
]
